from __future__ import annotations

from datetime import datetime
from decimal import Decimal
import math
import re
from typing import Literal, TypeAlias
from uuid import UUID

from pydantic import BaseModel, ConfigDict, JsonValue, field_validator, model_validator


MemoryType: TypeAlias = Literal[
    "decision",
    "preference",
    "risk",
    "customer_fact",
    "project_fact",
]
JsonSafeValue: TypeAlias = JsonValue
GROUP_MEMORY_CANDIDATE_MIN_CONFIDENCE = Decimal("0.85")

_FORBIDDEN_CONTENT_KEYS = frozenset(
    {
        "prompt",
        "response",
        "raw_text",
        "normalized_text",
        "api_key",
        "token",
        "telegram_user_id",
    }
)
_GROUP_FORBIDDEN_CONTENT_KEYS = _FORBIDDEN_CONTENT_KEYS | frozenset(
    {
        "text",
        "message_text",
        "chat_text",
        "caption",
        "transcript",
        "excerpt",
        "content",
        "raw_content",
        "raw_caption",
        "chat_id",
        "telegram_chat_id",
        "message_id",
        "telegram_message_id",
        "update_id",
        "telegram_update_id",
        "binding_id",
        "group_chat_ref",
        "source_id",
        "source_ref",
        "source_refs",
        "field_keys",
    }
)
_GROUP_BINDING_REF_PATTERN = re.compile(
    r"stage06-binding:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}"
)


class _StrictMemoryModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class MemorySourceRef(_StrictMemoryModel):
    source_kind: Literal["platform_record", "record_change_draft", "telegram_message"]
    source_id: UUID
    source_version: int | None
    field_keys: tuple[str, ...]

    @field_validator("source_version")
    @classmethod
    def _source_version_is_positive(cls, value: int | None) -> int | None:
        if value is not None and (isinstance(value, bool) or value < 1):
            raise ValueError("memory_source_version_invalid")
        return value

    @field_validator("field_keys")
    @classmethod
    def _field_keys_are_safe(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        if not value:
            raise ValueError("memory_source_field_keys_required")
        if len(value) != len(set(value)):
            raise ValueError("memory_source_field_keys_duplicate")
        for key in value:
            if isinstance(key, str) and key.casefold() in _FORBIDDEN_CONTENT_KEYS:
                raise ValueError("memory_forbidden_content_key")
            if not _is_lower_snake_case_key(key):
                raise ValueError("memory_source_field_key_invalid")
        return value


class MemoryScopeProjection(_StrictMemoryModel):
    workspace_id: UUID
    base_id: UUID | None = None
    table_id: UUID | None = None
    customer_record_id: UUID | None = None
    project_record_id: UUID | None = None
    group_chat_ref: str | None = None
    # Internal-only: generated by the confirmed-record materializer.  It is
    # deliberately optional so existing non-B3 projections remain compatible.
    identity_token: str | None = None

    @field_validator("group_chat_ref")
    @classmethod
    def _group_chat_ref_is_nonempty(cls, value: str | None) -> str | None:
        if value is not None and not value.strip():
            raise ValueError("memory_group_chat_ref_invalid")
        return value

    @field_validator("identity_token")
    @classmethod
    def _identity_token_is_hmac_hex(cls, value: str | None) -> str | None:
        if value is not None and not re.fullmatch(r"[0-9a-f]{64}", value):
            raise ValueError("memory_identity_token_invalid")
        return value


class MemoryMaterializationProjection(_StrictMemoryModel):
    memory_type: MemoryType
    scope: MemoryScopeProjection
    payload: dict[str, JsonSafeValue]
    source_refs: tuple[MemorySourceRef, ...]
    valid_until: datetime | None = None

    @field_validator("payload")
    @classmethod
    def _payload_keys_are_safe(
        cls,
        value: dict[str, JsonSafeValue],
    ) -> dict[str, JsonSafeValue]:
        _reject_forbidden_keys(value)
        return value

    @field_validator("source_refs")
    @classmethod
    def _source_refs_are_present(
        cls,
        value: tuple[MemorySourceRef, ...],
    ) -> tuple[MemorySourceRef, ...]:
        if not value:
            raise ValueError("memory_source_refs_required")
        return value

    @field_validator("valid_until")
    @classmethod
    def _valid_until_is_timezone_aware(cls, value: datetime | None) -> datetime | None:
        if value is not None and (value.tzinfo is None or value.utcoffset() is None):
            raise ValueError("memory_valid_until_timezone_required")
        return value

    @model_validator(mode="after")
    def _reject_forbidden_contract_keys(self) -> MemoryMaterializationProjection:
        _reject_forbidden_keys(self.model_dump(mode="json"))
        return self


class GroupMemoryCandidateProjection(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)

    candidate_type: MemoryType
    confidence: Decimal
    scope: MemoryScopeProjection
    normalized_payload: dict[str, JsonSafeValue]
    source_refs: tuple[MemorySourceRef, ...]
    valid_until: datetime | None = None

    @field_validator("confidence")
    @classmethod
    def _confidence_meets_deployed_floor(cls, value: Decimal) -> Decimal:
        if not value.is_finite() or value < GROUP_MEMORY_CANDIDATE_MIN_CONFIDENCE:
            raise ValueError("memory_candidate_confidence_below_threshold")
        if value > Decimal("1"):
            raise ValueError("memory_candidate_confidence_invalid")
        return value

    @field_validator("normalized_payload")
    @classmethod
    def _normalized_payload_is_bounded(
        cls,
        value: dict[str, JsonSafeValue],
    ) -> dict[str, JsonSafeValue]:
        if not value or len(value) > 16:
            raise ValueError("memory_payload_invalid")
        for key in value:
            if not _is_lower_snake_case_key(key):
                raise ValueError("memory_payload_invalid")
        _validate_group_payload(value, depth=0)
        return value

    @field_validator("source_refs")
    @classmethod
    def _source_ref_is_exact_group_projection(
        cls,
        value: tuple[MemorySourceRef, ...],
    ) -> tuple[MemorySourceRef, ...]:
        if len(value) != 1:
            raise ValueError("memory_group_source_invalid")
        source = value[0]
        if (
            source.source_kind != "telegram_message"
            or source.source_version is not None
            or source.field_keys != ("group_candidate_projection",)
        ):
            raise ValueError("memory_group_source_invalid")
        return value

    @field_validator("valid_until")
    @classmethod
    def _valid_until_is_timezone_aware(cls, value: datetime | None) -> datetime | None:
        if value is not None and (value.tzinfo is None or value.utcoffset() is None):
            raise ValueError("memory_valid_until_timezone_required")
        return value

    @model_validator(mode="after")
    def _scope_is_exact_opaque_group_binding(self) -> GroupMemoryCandidateProjection:
        group_chat_ref = self.scope.group_chat_ref
        if (
            group_chat_ref is None
            or _GROUP_BINDING_REF_PATTERN.fullmatch(group_chat_ref) is None
            or any(
                value is not None
                for value in (
                    self.scope.base_id,
                    self.scope.table_id,
                    self.scope.customer_record_id,
                    self.scope.project_record_id,
                    self.scope.identity_token,
                )
            )
        ):
            raise ValueError("memory_group_source_invalid")
        return self


def _is_lower_snake_case_key(value: object) -> bool:
    if not isinstance(value, str) or not value or len(value) > 120:
        return False
    return re.fullmatch(r"[a-z][a-z0-9]*(?:_[a-z0-9]+)*", value) is not None


def _reject_forbidden_keys(value: object) -> None:
    if isinstance(value, float) and not math.isfinite(value):
        raise ValueError("memory_non_finite_json_value")
    if isinstance(value, dict):
        for key, item in value.items():
            if isinstance(key, str) and key.casefold() in _FORBIDDEN_CONTENT_KEYS:
                raise ValueError("memory_forbidden_content_key")
            _reject_forbidden_keys(item)
    elif isinstance(value, (list, tuple)):
        for item in value:
            _reject_forbidden_keys(item)


def _validate_group_payload(value: object, *, depth: int) -> None:
    if depth > 4:
        raise ValueError("memory_payload_invalid")
    if isinstance(value, float) and not math.isfinite(value):
        raise ValueError("memory_non_finite_json_value")
    if isinstance(value, str):
        if len(value) > 500:
            raise ValueError("memory_payload_invalid")
        return
    if isinstance(value, dict):
        for key, item in value.items():
            if not _is_lower_snake_case_key(key):
                raise ValueError("memory_payload_invalid")
            if key.casefold() in _GROUP_FORBIDDEN_CONTENT_KEYS:
                raise ValueError("memory_forbidden_content_key")
            _validate_group_payload(item, depth=depth + 1)
        return
    if isinstance(value, (list, tuple)):
        if len(value) > 20:
            raise ValueError("memory_payload_invalid")
        for item in value:
            _validate_group_payload(item, depth=depth + 1)
