from dataclasses import dataclass
from typing import Literal


STAGE05_SKILL_MANIFEST_VERSION = "stage05-skills-v1"

SkillPriority = Literal["P0", "P1"]
SkillExecutionMode = Literal["sidecar", "draft", "manual_review", "future_scope"]


@dataclass(frozen=True)
class Stage05SkillManifest:
    skill_id: str
    priority: SkillPriority
    layer: str
    source_skill: str
    owning_agent: str
    primary_agent_node: str
    primary_endpoint: str
    description: str
    positive_triggers: tuple[str, ...]
    negative_triggers: tuple[str, ...]
    required_entities: tuple[str, ...]
    optional_entities: tuple[str, ...]
    allowed_tools: tuple[str, ...]
    forbidden_actions: tuple[str, ...]
    fallback: str
    stage_allowed: bool
    execution_mode: SkillExecutionMode


_COMMON_FORBIDDEN = (
    "raw_sql",
    "direct_provider_call",
    "direct_telegram_send",
    "self_confirmation",
    "secret_access",
)


_REGISTRY: tuple[Stage05SkillManifest, ...] = (
    Stage05SkillManifest(
        skill_id="project-base",
        priority="P0",
        layer="L2 Bitable/Data",
        source_skill="lark-base",
        owning_agent="Operations Supervisor Agent",
        primary_agent_node="stage05_supervisor",
        primary_endpoint="Bitable-like records/views",
        description="Use when a Stage05 skill must resolve table, view, record, status, endpoint or audit landing behavior.",
        positive_triggers=("record", "draft", "view", "table", "endpoint", "audit"),
        negative_triggers=("raw spreadsheet clone", "unscoped data analysis"),
        required_entities=(),
        optional_entities=("message_id", "customer_id", "record_id"),
        allowed_tools=("create_service_draft", "record_audit_event", "query_bitable_view"),
        forbidden_actions=_COMMON_FORBIDDEN,
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="sidecar",
    ),
    Stage05SkillManifest(
        skill_id="project-shared",
        priority="P0",
        layer="L0 Governance",
        source_skill="lark-shared",
        owning_agent="Operations Supervisor Agent",
        primary_agent_node="stage05_supervisor",
        primary_endpoint="permission_snapshot/audit",
        description="Use when a Stage05 skill needs identity, permission, confirmation, stage policy or high-risk action gating.",
        positive_triggers=("permission", "role", "confirmation", "policy", "scope"),
        negative_triggers=("bypass permission", "retry as stronger actor"),
        required_entities=(),
        optional_entities=("actor_type", "actor_id", "role"),
        allowed_tools=("evaluate_permission", "record_policy_denial", "record_audit_event"),
        forbidden_actions=_COMMON_FORBIDDEN + ("privilege_escalation",),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="sidecar",
    ),
    Stage05SkillManifest(
        skill_id="project-im",
        priority="P0",
        layer="L1 Channel/Event",
        source_skill="lark-im",
        owning_agent="Message Intake Router Agent",
        primary_agent_node="message_intake_router",
        primary_endpoint="telegram_inbox/telegram_send_requests",
        description="Use when Stage05 input or output is tied to Telegram messages, chat binding, reply drafts or send-request evidence.",
        positive_triggers=("telegram", "message", "reply", "chat", "send request"),
        negative_triggers=("customer group send", "direct bot api"),
        required_entities=(),
        optional_entities=("telegram_message_id", "chat_id", "telegram_user_id"),
        allowed_tools=("query_telegram_inbox_message", "create_customer_reply_send_request"),
        forbidden_actions=_COMMON_FORBIDDEN + ("customer_group_send",),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="sidecar",
    ),
    Stage05SkillManifest(
        skill_id="project-event",
        priority="P0",
        layer="L1 Channel/Event",
        source_skill="lark-event",
        owning_agent="Operations Supervisor Agent",
        primary_agent_node="stage05_supervisor",
        primary_endpoint="outbox_events/worker evidence",
        description="Use when Stage05 needs bounded event, webhook, worker, retry or idempotency evidence.",
        positive_triggers=("event", "webhook", "worker", "retry", "idempotency"),
        negative_triggers=("infinite polling", "unsafe retry"),
        required_entities=(),
        optional_entities=("trace_id", "idempotency_key"),
        allowed_tools=("enqueue_outbox_event", "record_worker_result"),
        forbidden_actions=_COMMON_FORBIDDEN + ("unsafe_retry",),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="sidecar",
    ),
    Stage05SkillManifest(
        skill_id="project-skill-maker",
        priority="P0",
        layer="L0 Governance",
        source_skill="lark-skill-maker",
        owning_agent="Operations Supervisor Agent",
        primary_agent_node="stage05_supervisor",
        primary_endpoint="skill manifest docs/tests",
        description="Use when defining, changing or validating project Agent skill contracts and trigger rules.",
        positive_triggers=("skill", "manifest", "registry", "capability", "trigger"),
        negative_triggers=("dynamic marketplace", "codex skill install"),
        required_entities=(),
        optional_entities=("skill_id",),
        allowed_tools=("read_skill_manifest", "validate_skill_manifest"),
        forbidden_actions=_COMMON_FORBIDDEN + ("dynamic_skill_install",),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="sidecar",
    ),
    Stage05SkillManifest(
        skill_id="project-task",
        priority="P1",
        layer="L4 Workflow",
        source_skill="lark-task",
        owning_agent="Operations Supervisor Agent",
        primary_agent_node="stage05_supervisor",
        primary_endpoint="agent_review_queue/pending_confirmation",
        description="Use when a Stage05 outcome must become pending work, manual review, needs-more-info or operator handoff.",
        positive_triggers=("manual review", "pending", "task", "handoff", "needs more info"),
        negative_triggers=("auto execution",),
        required_entities=(),
        optional_entities=("review_reason", "draft_id"),
        allowed_tools=("create_agent_review_item", "update_service_draft_status"),
        forbidden_actions=_COMMON_FORBIDDEN + ("auto_execute_task",),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="manual_review",
    ),
    Stage05SkillManifest(
        skill_id="project-contact",
        priority="P1",
        layer="L1 Channel/Event",
        source_skill="lark-contact",
        owning_agent="Message Intake Router Agent",
        primary_agent_node="message_intake_router",
        primary_endpoint="customer binding/contact hints",
        description="Use when resolving Telegram sender, customer, operator, invitee or contact hints.",
        positive_triggers=("email", "invitee", "contact", "sender", "customer binding"),
        negative_triggers=("permission by email",),
        required_entities=(),
        optional_entities=("invitee_hint", "telegram_user_id", "customer_id"),
        allowed_tools=("query_customer_binding", "query_operator_identity"),
        forbidden_actions=_COMMON_FORBIDDEN + ("treat_contact_as_permission",),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="sidecar",
    ),
    Stage05SkillManifest(
        skill_id="project-approval",
        priority="P1",
        layer="L4 Workflow",
        source_skill="lark-approval",
        owning_agent="Operations Supervisor Agent",
        primary_agent_node="stage05_supervisor",
        primary_endpoint="pending_confirmation/service_drafts",
        description="Use when Stage05 needs confirmation, rejection, more-info, escalation or approval-like state transition evidence.",
        positive_triggers=("confirm", "approve", "reject", "escalate", "confirmation"),
        negative_triggers=("agent self approve",),
        required_entities=(),
        optional_entities=("service_draft_id", "confirmation_action"),
        allowed_tools=("confirm_service_draft", "record_audit_event"),
        forbidden_actions=_COMMON_FORBIDDEN + ("agent_self_approval",),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="manual_review",
    ),
    Stage05SkillManifest(
        skill_id="project-tabular-analysis",
        priority="P1",
        layer="L2 Bitable/Data",
        source_skill="lark-sheets",
        owning_agent="Stats Risk Agent",
        primary_agent_node="message_intake_router",
        primary_endpoint="Bitable-like spend/query views",
        description="Use when Stage05 input asks for tabular values, spend, balance, grouped counts, totals or table-shaped output.",
        positive_triggers=("spend", "balance", "table", "total", "消耗", "余额"),
        negative_triggers=("raw sql", "provider readback"),
        required_entities=(),
        optional_entities=("account_hint", "date_range"),
        allowed_tools=("query_bitable_view", "aggregate_existing_records"),
        forbidden_actions=_COMMON_FORBIDDEN + ("provider_readback", "invent_financial_fact"),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="sidecar",
    ),
    Stage05SkillManifest(
        skill_id="project-tool-discovery",
        priority="P1",
        layer="L0 Governance",
        source_skill="lark-openapi-explorer",
        owning_agent="Operations Supervisor Agent",
        primary_agent_node="stage05_supervisor",
        primary_endpoint="future Tool Gateway design",
        description="Use when an approved later-stage requirement needs controlled Tool Gateway research before external API implementation.",
        positive_triggers=("tool discovery", "provider api", "openapi", "adapter"),
        negative_triggers=("runtime raw api call",),
        required_entities=(),
        optional_entities=("approved_requirement",),
        allowed_tools=("read_official_docs", "draft_tool_contract"),
        forbidden_actions=_COMMON_FORBIDDEN + ("raw_external_api_call",),
        fallback="future_scope",
        stage_allowed=True,
        execution_mode="future_scope",
    ),
    Stage05SkillManifest(
        skill_id="project-daily-operations-workflow",
        priority="P1",
        layer="L4 Workflow",
        source_skill="lark-workflow-standup-report",
        owning_agent="Customer Reporting Agent",
        primary_agent_node="message_intake_router",
        primary_endpoint="future report/manual_review",
        description="Use when the user asks for daily customer/company operations report, digest or today/yesterday summary.",
        positive_triggers=("daily report", "日报", "today report", "digest", "summary"),
        negative_triggers=("send customer group now",),
        required_entities=(),
        optional_entities=("date_range", "customer_id"),
        allowed_tools=("create_agent_review_item",),
        forbidden_actions=_COMMON_FORBIDDEN + ("generate_report_now", "customer_group_send"),
        fallback="future_scope",
        stage_allowed=True,
        execution_mode="future_scope",
    ),
    Stage05SkillManifest(
        skill_id="project-period-summary-workflow",
        priority="P1",
        layer="L4 Workflow",
        source_skill="lark-workflow-meeting-summary",
        owning_agent="Customer Reporting Agent",
        primary_agent_node="message_intake_router",
        primary_endpoint="future period summary/manual_review",
        description="Use when the user asks for weekly, monthly or period operations summary.",
        positive_triggers=("weekly", "monthly", "period", "周报", "月报", "summary"),
        negative_triggers=("meeting transcript",),
        required_entities=(),
        optional_entities=("date_range", "customer_id"),
        allowed_tools=("create_agent_review_item",),
        forbidden_actions=_COMMON_FORBIDDEN + ("generate_report_now",),
        fallback="future_scope",
        stage_allowed=True,
        execution_mode="future_scope",
    ),
    Stage05SkillManifest(
        skill_id="recharge-draft",
        priority="P1",
        layer="L3 Business Atomic",
        source_skill="lark-base/lark-task",
        owning_agent="Recharge Draft Agent",
        primary_agent_node="recharge_draft_agent",
        primary_endpoint="service_drafts.draft_type=recharge",
        description="Use when the user asks to prepare a recharge draft for an advertising account.",
        positive_triggers=("recharge", "top up", "充", "充值", "USDT", "USD"),
        negative_triggers=("provider already succeeded",),
        required_entities=("account_hint", "amount", "currency"),
        optional_entities=("deadline", "note"),
        allowed_tools=("create_service_draft",),
        forbidden_actions=_COMMON_FORBIDDEN + ("execute_recharge", "claim_success"),
        fallback="needs_more_info",
        stage_allowed=True,
        execution_mode="draft",
    ),
    Stage05SkillManifest(
        skill_id="customer-reply-draft",
        priority="P1",
        layer="L3 Business Atomic",
        source_skill="lark-im/lark-approval",
        owning_agent="Customer Reply Draft Agent",
        primary_agent_node="customer_reply_draft_agent",
        primary_endpoint="service_drafts.draft_type=customer_reply",
        description="Use when the user asks to draft a safe Telegram customer reply.",
        positive_triggers=("reply", "respond", "回复", "告诉客户", "回他说"),
        negative_triggers=("send now without confirmation",),
        required_entities=(),
        optional_entities=("reply_text", "reply_topic"),
        allowed_tools=("create_service_draft", "create_customer_reply_send_request"),
        forbidden_actions=_COMMON_FORBIDDEN + ("send_without_confirmation",),
        fallback="pending_confirmation",
        stage_allowed=True,
        execution_mode="draft",
    ),
    Stage05SkillManifest(
        skill_id="bm-invite-draft",
        priority="P1",
        layer="L3 Business Atomic",
        source_skill="lark-task/lark-contact",
        owning_agent="BM Invite Draft Agent",
        primary_agent_node="bm_invite_draft_agent",
        primary_endpoint="service_drafts.draft_type=bm_invite",
        description="Use when the user asks to prepare a BM invite draft.",
        positive_triggers=("BM", "invite", "邀请", "email"),
        negative_triggers=("send invite now",),
        required_entities=("bm_hint", "invitee_hint"),
        optional_entities=("role",),
        allowed_tools=("create_service_draft",),
        forbidden_actions=_COMMON_FORBIDDEN + ("execute_bm_invite",),
        fallback="needs_more_info",
        stage_allowed=True,
        execution_mode="draft",
    ),
    Stage05SkillManifest(
        skill_id="card-binding-draft",
        priority="P1",
        layer="L3 Business Atomic",
        source_skill="lark-shared/lark-task",
        owning_agent="Card Binding Draft Agent",
        primary_agent_node="card_binding_draft_agent",
        primary_endpoint="service_drafts.draft_type=card_binding",
        description="Use when the user asks to prepare a card binding draft using safe payment references.",
        positive_triggers=("bind card", "绑卡", "payment profile", "card_profile"),
        negative_triggers=("raw card number", "CVV"),
        required_entities=("account_hint",),
        optional_entities=("payment_profile_hint",),
        allowed_tools=("create_service_draft",),
        forbidden_actions=_COMMON_FORBIDDEN + ("store_raw_card", "store_cvv", "execute_card_binding"),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="draft",
    ),
    Stage05SkillManifest(
        skill_id="account-exception-marking",
        priority="P1",
        layer="L3 Business Atomic",
        source_skill="lark-base/lark-shared",
        owning_agent="Account Inventory Agent",
        primary_agent_node="account_inventory_agent",
        primary_endpoint="account_inventory/account_status_events",
        description="Use when the user reports a high-confidence account blocked, disabled or risk-controlled state.",
        positive_triggers=("blocked", "disabled", "risk controlled", "封号", "风控", "不能用了"),
        negative_triggers=("replace account automatically",),
        required_entities=("account_hint", "target_status"),
        optional_entities=("reason",),
        allowed_tools=("mark_account_inventory_exception",),
        forbidden_actions=_COMMON_FORBIDDEN + ("auto_replace_account", "auto_reserve_account"),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="draft",
    ),
    Stage05SkillManifest(
        skill_id="manual-review-handoff",
        priority="P1",
        layer="L4 Workflow",
        source_skill="lark-task/lark-approval",
        owning_agent="Operations Supervisor Agent",
        primary_agent_node="stage05_supervisor",
        primary_endpoint="agent_review_queue/manual_review",
        description="Use when the user request is ambiguous, unsupported, future-scope, policy-blocked or missing critical context.",
        positive_triggers=("manual_review", "unknown", "unsupported", "future_scope"),
        negative_triggers=("silent success",),
        required_entities=(),
        optional_entities=("reason",),
        allowed_tools=("create_agent_review_item", "record_audit_event"),
        forbidden_actions=_COMMON_FORBIDDEN + ("drop_without_evidence",),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="manual_review",
    ),
    Stage05SkillManifest(
        skill_id="spend-query",
        priority="P1",
        layer="L3 Business Atomic",
        source_skill="lark-sheets/lark-base",
        owning_agent="Stats Risk Agent",
        primary_agent_node="message_intake_router",
        primary_endpoint="future spend query/manual_review",
        description="Use when the user asks for spend, balance, cost or remaining amount facts.",
        positive_triggers=("spend", "balance", "消耗", "余额", "花了多少", "还剩多少"),
        negative_triggers=("provider readback now",),
        required_entities=(),
        optional_entities=("account_hint", "date_range"),
        allowed_tools=("record_skill_candidate_only",),
        forbidden_actions=_COMMON_FORBIDDEN + ("provider_readback", "invent_financial_fact"),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="manual_review",
    ),
    Stage05SkillManifest(
        skill_id="spend-table",
        priority="P1",
        layer="L3 Business Atomic",
        source_skill="lark-sheets/lark-base",
        owning_agent="Stats Risk Agent",
        primary_agent_node="message_intake_router",
        primary_endpoint="future spend table/manual_review",
        description="Use when the user asks to build or inspect a spend table or table-shaped spend view.",
        positive_triggers=("spend table", "消耗表", "table", "view"),
        negative_triggers=("generate report",),
        required_entities=(),
        optional_entities=("date_range", "customer_id"),
        allowed_tools=("record_skill_candidate_only",),
        forbidden_actions=_COMMON_FORBIDDEN + ("create_spend_table_now", "provider_readback"),
        fallback="manual_review",
        stage_allowed=True,
        execution_mode="manual_review",
    ),
)


_REGISTRY_BY_ID = {skill.skill_id: skill for skill in _REGISTRY}


def get_stage05_skill_registry() -> tuple[Stage05SkillManifest, ...]:
    return _REGISTRY


def get_skill_manifest(skill_id: str) -> Stage05SkillManifest:
    return _REGISTRY_BY_ID[skill_id]


def has_skill(skill_id: str) -> bool:
    return skill_id in _REGISTRY_BY_ID


__all__ = [
    "STAGE05_SKILL_MANIFEST_VERSION",
    "Stage05SkillManifest",
    "get_skill_manifest",
    "get_stage05_skill_registry",
    "has_skill",
]
