from dataclasses import dataclass
from typing import Literal


STAGE06_SKILL_MANIFEST_VERSION = "stage06-larksuite-skills-v1"

SkillStatus = Literal["active", "planned", "future", "reference_only"]


@dataclass(frozen=True)
class Stage06SkillManifest:
    skill_id: str
    source_skill: str
    status: SkillStatus
    layer: str
    name: str
    description: str
    when_to_use: tuple[str, ...]
    not_for: tuple[str, ...]
    resource_patterns: tuple[str, ...]
    positive_triggers: tuple[str, ...]
    negative_triggers: tuple[str, ...]
    required_context: tuple[str, ...]
    optional_context: tuple[str, ...]
    allowed_actions: tuple[str, ...]
    forbidden_actions: tuple[str, ...]
    output_contract: str
    confirmation_policy: str
    fallback: str


_COMMON_FORBIDDEN = (
    "raw_sql",
    "feishu_api_call",
    "lark_cli_runtime_call",
    "direct_telegram_send",
    "self_confirmation",
    "secret_access",
)


def _manifest(
    *,
    skill_id: str,
    source_skill: str,
    status: SkillStatus,
    layer: str,
    name: str,
    description: str,
    triggers: tuple[str, ...],
    not_for: tuple[str, ...],
    resource_patterns: tuple[str, ...],
    required_context: tuple[str, ...],
    optional_context: tuple[str, ...] = (),
    allowed_actions: tuple[str, ...] = (),
    negative_triggers: tuple[str, ...] = (),
    forbidden_actions: tuple[str, ...] = (),
    output_contract: str = "skill_evidence",
    confirmation_policy: str = "read_only",
    fallback: str = "manual_review",
) -> Stage06SkillManifest:
    return Stage06SkillManifest(
        skill_id=skill_id,
        source_skill=source_skill,
        status=status,
        layer=layer,
        name=name,
        description=description,
        when_to_use=triggers,
        not_for=not_for,
        resource_patterns=resource_patterns,
        positive_triggers=triggers,
        negative_triggers=negative_triggers,
        required_context=required_context,
        optional_context=optional_context,
        allowed_actions=allowed_actions,
        forbidden_actions=_COMMON_FORBIDDEN + forbidden_actions,
        output_contract=output_contract,
        confirmation_policy=confirmation_policy,
        fallback=fallback,
    )


_REGISTRY: tuple[Stage06SkillManifest, ...] = (
    _manifest(
        skill_id="platform-approval",
        source_skill="lark-approval",
        status="active",
        layer="L3 Work Object",
        name="Approval And Confirmation",
        description="Draft review, confirmation, rejection, approval queue and escalation flows.",
        triggers=("approve", "confirm", "reject", "approval", "pending", "确认", "审批"),
        not_for=("ordinary task management", "self approval", "approval definition builder"),
        resource_patterns=("draft_id", "record_change_draft", "approval"),
        required_context=("actor_user_id",),
        optional_context=("draft_id", "record_id", "base_id"),
        allowed_actions=("record_change_draft.review", "record_change_draft.confirmation_request"),
        negative_triggers=("skip approval", "self approve", "直接执行"),
        forbidden_actions=("agent_self_approval",),
        output_contract="approval_decision_or_pending_draft",
        confirmation_policy="required_for_write_send_destructive",
        fallback="manual_review",
    ),
    _manifest(
        skill_id="platform-app-ops-reference",
        source_skill="lark-apps",
        status="reference_only",
        layer="L0 Governance and Policy",
        name="Application Operations Reference",
        description="Reference for release, hosting, logs and environment guardrails.",
        triggers=("deploy", "release", "上线", "日志", "env"),
        not_for=("project runtime execution", "Mini App implementation"),
        resource_patterns=("deployment", "env", "log"),
        required_context=(),
        forbidden_actions=("miaoda_runtime_call",),
        output_contract="reference_only",
        confirmation_policy="not_executable",
        fallback="reference_only",
    ),
    _manifest(
        skill_id="template-attendance",
        source_skill="lark-attendance",
        status="future",
        layer="L3 Work Object",
        name="Attendance Template",
        description="Future HR/timekeeping template for attendance-like records.",
        triggers=("attendance", "check-in", "考勤", "打卡"),
        not_for=("current Stage06 core runtime",),
        resource_patterns=("attendance", "check_in"),
        required_context=("workspace_id",),
        optional_context=("user_id", "date_range"),
        confirmation_policy="not_executable",
        fallback="future_scope",
    ),
    _manifest(
        skill_id="platform-base",
        source_skill="lark-base",
        status="active",
        layer="L2 Workspace Resource",
        name="Multidimensional Base",
        description="Workspace, base, table, field, record, view, form-lite and permission-scoped operations.",
        triggers=("base", "table", "record", "field", "view", "schema", "多维表格", "记录", "字段", "表"),
        not_for=("file import itself", "raw spreadsheet cell editing", "Feishu API compatibility"),
        resource_patterns=("workspace_id", "base_id", "table_id", "view_id", "record_id"),
        required_context=("workspace",),
        optional_context=("base_id", "table_id", "view_id", "record_id"),
        allowed_actions=("schema.inspect", "record.query", "record_change_draft.create"),
        negative_triggers=("raw sql", "provider write", "Feishu API"),
        forbidden_actions=("direct_record_commit_without_confirmation",),
        output_contract="table_resource_answer_or_draft",
        confirmation_policy="draft_required_for_write",
        fallback="ask_for_missing_context",
    ),
    _manifest(
        skill_id="platform-calendar",
        source_skill="lark-calendar",
        status="planned",
        layer="L3 Work Object",
        name="Calendar",
        description="Planned generic scheduling skill for calendar-like tables and event resources.",
        triggers=("calendar", "schedule", "meeting", "日程", "会议"),
        not_for=("historical video meeting artifacts", "ordinary tasks"),
        resource_patterns=("calendar", "event", "meeting"),
        required_context=("workspace_id",),
        optional_context=("date_range", "assignee_id"),
        confirmation_policy="not_executable",
        fallback="planned_skill",
    ),
    _manifest(
        skill_id="platform-contact",
        source_skill="lark-contact",
        status="active",
        layer="L1 Channel and Event",
        name="Contact Resolution",
        description="Resolve Telegram users, workspace members, customer contacts and assignees.",
        triggers=("contact", "email", "assignee", "member", "user", "负责人", "联系人"),
        not_for=("using contact as permission", "unrestricted member enumeration"),
        resource_patterns=("actor_user_id", "telegram_user_id", "email", "member_id"),
        required_context=("workspace_id",),
        optional_context=("telegram_user_id", "email", "member_id"),
        allowed_actions=("member.resolve", "contact.resolve"),
        negative_triggers=("permission by email", "list every user"),
        forbidden_actions=("treat_contact_as_permission",),
        output_contract="resolved_contact_or_clarification",
        fallback="ask_for_missing_context",
    ),
    _manifest(
        skill_id="platform-doc",
        source_skill="lark-doc",
        status="planned",
        layer="L2 Workspace Resource",
        name="Document",
        description="Planned skill for SOPs, notes and generated documents.",
        triggers=("document", "doc", "SOP", "note", "文档"),
        not_for=("table record operation", "spreadsheet values", "document comments"),
        resource_patterns=("document_id", "doc_id"),
        required_context=("workspace_id",),
        optional_context=("document_id",),
        confirmation_policy="not_executable",
        fallback="planned_skill",
    ),
    _manifest(
        skill_id="platform-file-import",
        source_skill="lark-drive",
        status="active",
        layer="L2 Workspace Resource",
        name="File Import",
        description="CSV/Excel import, attachment metadata and future file-resource handling.",
        triggers=("import", "upload", "file", "csv", "excel", "导入", "附件"),
        not_for=("editing document body", "cloud drive parity"),
        resource_patterns=(".csv", ".xlsx", "attachment", "file_id"),
        required_context=("workspace_id",),
        optional_context=("base_id", "file_id", "filename"),
        allowed_actions=("import.preview", "import.commit", "template.save"),
        negative_triggers=("edit document body", "move cloud folder"),
        forbidden_actions=("unsafe_file_execute",),
        output_contract="import_preview_or_missing_file",
        confirmation_policy="confirmation_required_for_import_commit",
        fallback="ask_for_file",
    ),
    _manifest(
        skill_id="platform-event",
        source_skill="lark-event",
        status="active",
        layer="L1 Channel and Event",
        name="Event Intake",
        description="Telegram webhook/polling, bounded subscribers, queue events and smoke evidence.",
        triggers=("event", "webhook", "poll", "queue", "worker", "事件"),
        not_for=("unbounded polling", "business decision itself"),
        resource_patterns=("telegram_update_id", "event_id", "trace_id"),
        required_context=(),
        optional_context=("telegram_update_id", "trace_id"),
        allowed_actions=("event.consume_bounded", "event.record_evidence"),
        negative_triggers=("infinite polling", "unsafe retry"),
        forbidden_actions=("unbounded_polling",),
        output_contract="bounded_event_evidence",
    ),
    _manifest(
        skill_id="platform-telegram-im",
        source_skill="lark-im",
        status="active",
        layer="L1 Channel and Event",
        name="Telegram IM",
        description="Telegram messages, mentions, chats, inline buttons, files and reply drafts.",
        triggers=("telegram", "message", "chat", "reply", "send", "mention", "消息", "回复"),
        not_for=("direct send without confirmation", "Feishu IM"),
        resource_patterns=("telegram_chat_id", "telegram_user_id", "message_id"),
        required_context=("telegram_chat_id",),
        optional_context=("telegram_user_id", "message_id", "alias"),
        allowed_actions=("telegram.message.read", "notification_request.create"),
        negative_triggers=("send now without confirmation", "broad group send"),
        forbidden_actions=("broad_group_send", "send_without_confirmation"),
        output_contract="telegram_answer_or_send_draft",
        confirmation_policy="draft_required_for_send",
    ),
    _manifest(
        skill_id="platform-mail",
        source_skill="lark-mail",
        status="planned",
        layer="L1 Channel and Event",
        name="Mail",
        description="Planned email channel adapter. Mail content is untrusted external input.",
        triggers=("mail", "email", "邮件"),
        not_for=("Telegram chat", "pure contact lookup"),
        resource_patterns=("email_message_id", "mailbox"),
        required_context=("workspace_id",),
        optional_context=("email_message_id",),
        negative_triggers=("telegram", "calendar"),
        forbidden_actions=("trust_external_mail_content",),
        output_contract="planned_mail_action",
        confirmation_policy="not_executable",
        fallback="planned_skill",
    ),
    _manifest(
        skill_id="platform-markdown-doc",
        source_skill="lark-markdown",
        status="planned",
        layer="L2 Workspace Resource",
        name="Markdown Document",
        description="Planned skill for Markdown snippets, docs and diff-style edits.",
        triggers=("markdown", "md", "patch", "diff"),
        not_for=("cloud file search", "table records"),
        resource_patterns=(".md", "markdown"),
        required_context=("workspace_id",),
        optional_context=("document_id",),
        confirmation_policy="not_executable",
        fallback="planned_skill",
    ),
    _manifest(
        skill_id="platform-minutes",
        source_skill="lark-minutes",
        status="future",
        layer="L2 Workspace Resource",
        name="Minutes",
        description="Future meeting-knowledge artifact skill.",
        triggers=("minutes", "transcript", "recording", "妙记", "逐字稿"),
        not_for=("current Stage06 table runtime",),
        resource_patterns=("minute_id", "transcript"),
        required_context=("workspace_id",),
        optional_context=("minute_id",),
        output_contract="future_minutes_action",
        confirmation_policy="not_executable",
        fallback="future_scope",
    ),
    _manifest(
        skill_id="platform-note",
        source_skill="lark-note",
        status="future",
        layer="L2 Workspace Resource",
        name="Meeting Note",
        description="Future known-note lookup skill.",
        triggers=("note", "纪要"),
        not_for=("generic table note field", "document title search"),
        resource_patterns=("note_id",),
        required_context=("workspace_id",),
        optional_context=("note_id",),
        output_contract="future_note_action",
        confirmation_policy="not_executable",
        fallback="future_scope",
    ),
    _manifest(
        skill_id="template-okr",
        source_skill="lark-okr",
        status="future",
        layer="L3 Work Object",
        name="OKR Template",
        description="Future OKR template built from tables, tasks and progress records.",
        triggers=("okr", "objective", "key result", "目标"),
        not_for=("performance evaluation",),
        resource_patterns=("okr", "objective"),
        required_context=("workspace_id",),
        optional_context=("cycle_id",),
        output_contract="future_template",
        confirmation_policy="not_executable",
        fallback="future_scope",
    ),
    _manifest(
        skill_id="platform-tool-discovery",
        source_skill="lark-openapi-explorer",
        status="active",
        layer="L0 Governance and Policy",
        name="Tool Discovery",
        description="Project Tool Gateway discovery, service schema introspection and missing-tool reporting.",
        triggers=("tool", "capability", "unsupported", "discover", "能力", "工具"),
        not_for=("Feishu OpenAPI discovery", "raw external API call"),
        resource_patterns=("tool_name", "capability"),
        required_context=(),
        optional_context=("requested_capability",),
        allowed_actions=("tool_catalog.inspect", "missing_tool.report"),
        negative_triggers=("call Feishu API", "raw API now"),
        forbidden_actions=("raw_external_api_call",),
        output_contract="tool_capability_report",
    ),
    _manifest(
        skill_id="platform-shared-policy",
        source_skill="lark-shared",
        status="active",
        layer="L0 Governance and Policy",
        name="Shared Policy",
        description="Identity, permissions, scope intersection, JSON/error contract and high-risk gates.",
        triggers=("permission", "scope", "policy", "identity", "confirmation", "权限", "确认"),
        not_for=("business answer by itself",),
        resource_patterns=("actor_user_id", "role", "scope_policy"),
        required_context=("actor_user_id",),
        optional_context=("role", "telegram_chat_id", "digital_employee_id"),
        allowed_actions=("permission.evaluate", "audit.record", "policy.deny"),
        negative_triggers=("bypass permission", "ignore scope"),
        forbidden_actions=("privilege_escalation",),
        output_contract="policy_decision_or_guardrail",
        confirmation_policy="required_for_write_send_destructive",
    ),
    _manifest(
        skill_id="platform-tabular-analysis",
        source_skill="lark-sheets",
        status="active",
        layer="L2 Workspace Resource",
        name="Tabular Analysis",
        description="Table analysis, summaries, totals and chart/dashboard-lite planning over visible data.",
        triggers=("summarize", "analyze", "total", "formula", "chart", "统计", "分析", "汇总", "总结"),
        not_for=("full spreadsheet parity", "hidden fields", "raw SQL"),
        resource_patterns=("table_id", "view_id", "field_key"),
        required_context=("view_id",),
        optional_context=("table_id", "field_key", "date_range"),
        allowed_actions=("record.query", "table.summarize", "statistics.preview"),
        negative_triggers=("raw sql", "hidden field"),
        forbidden_actions=("invent_fact", "read_hidden_field"),
        output_contract="analysis_answer_with_citations",
        fallback="ask_for_missing_context",
    ),
    _manifest(
        skill_id="platform-skill-maker",
        source_skill="lark-skill-maker",
        status="active",
        layer="L0 Governance and Policy",
        name="Skill Maker",
        description="Authoring, validating and testing future project-native skill manifests.",
        triggers=("skill", "manifest", "registry", "capability", "技能"),
        not_for=("runtime user-installed arbitrary skills",),
        resource_patterns=("skill_id", "manifest_version"),
        required_context=(),
        optional_context=("skill_id",),
        allowed_actions=("skill_manifest.validate", "skill_fixture.generate"),
        negative_triggers=("install arbitrary code",),
        forbidden_actions=("dynamic_skill_install",),
        output_contract="skill_manifest_review",
    ),
    _manifest(
        skill_id="platform-slides-export",
        source_skill="lark-slides",
        status="future",
        layer="L2 Workspace Resource",
        name="Slides Export",
        description="Future report export skill for slide-like artifacts.",
        triggers=("slides", "presentation", "deck", "幻灯片"),
        not_for=("current Stage06 runtime",),
        resource_patterns=("slide_id",),
        required_context=("workspace_id",),
        output_contract="future_export_action",
        confirmation_policy="not_executable",
        fallback="future_scope",
    ),
    _manifest(
        skill_id="platform-task",
        source_skill="lark-task",
        status="active",
        layer="L3 Work Object",
        name="Task And Work Item",
        description="Work items, follow-ups, assignments, queues and digital employee task logs.",
        triggers=("task", "todo", "follow up", "assign", "待办", "任务", "跟进"),
        not_for=("approval task", "table schema operation"),
        resource_patterns=("task_id", "assignee_id", "record_id"),
        required_context=("workspace_id",),
        optional_context=("record_id", "assignee_id", "due_date"),
        allowed_actions=("task.create_draft", "task.query", "work_item.update_draft"),
        negative_triggers=("approval instance", "schema"),
        forbidden_actions=("auto_assign_without_permission",),
        output_contract="task_answer_or_draft",
        confirmation_policy="draft_required_for_write",
        fallback="ask_for_missing_context",
    ),
    _manifest(
        skill_id="platform-meeting-history",
        source_skill="lark-vc",
        status="future",
        layer="L2 Workspace Resource",
        name="Meeting History",
        description="Future historical meeting artifact skill.",
        triggers=("meeting history", "recording", "会议记录"),
        not_for=("future schedule", "active meeting join"),
        resource_patterns=("meeting_id",),
        required_context=("workspace_id",),
        output_contract="future_meeting_history_action",
        confirmation_policy="not_executable",
        fallback="future_scope",
    ),
    _manifest(
        skill_id="platform-live-meeting-agent-reference",
        source_skill="lark-vc-agent",
        status="reference_only",
        layer="L5 Live Agent Runtime",
        name="Live Meeting Agent Reference",
        description="Reference for high-risk live meeting participation; not executable in Stage06.",
        triggers=("join meeting", "active meeting", "live meeting", "视频会议", "实时", "发言", "加入"),
        not_for=("Telegram-first table workflows", "Stage06 active runtime"),
        resource_patterns=("active_meeting_id",),
        required_context=("workspace_id",),
        forbidden_actions=("join_live_meeting",),
        output_contract="reference_only",
        confirmation_policy="not_executable",
        fallback="reference_only",
    ),
    _manifest(
        skill_id="platform-diagram-board",
        source_skill="lark-whiteboard",
        status="future",
        layer="L2 Workspace Resource",
        name="Diagram Board",
        description="Future visual diagram/whiteboard skill.",
        triggers=("whiteboard", "diagram", "flowchart", "画板", "流程图"),
        not_for=("current Stage06 runtime",),
        resource_patterns=("board_id", "diagram"),
        required_context=("workspace_id",),
        output_contract="future_diagram_action",
        confirmation_policy="not_executable",
        fallback="future_scope",
    ),
    _manifest(
        skill_id="platform-knowledge-space",
        source_skill="lark-wiki",
        status="planned",
        layer="L2 Workspace Resource",
        name="Knowledge Space",
        description="Planned SOP and knowledge-space organization skill.",
        triggers=("wiki", "knowledge", "SOP", "知识库"),
        not_for=("table record editing", "file upload itself"),
        resource_patterns=("knowledge_space_id", "wiki_node_id"),
        required_context=("workspace_id",),
        optional_context=("knowledge_space_id",),
        output_contract="planned_knowledge_action",
        confirmation_policy="not_executable",
        fallback="planned_skill",
    ),
    _manifest(
        skill_id="workflow-period-summary",
        source_skill="lark-workflow-meeting-summary",
        status="planned",
        layer="L4 Workflow Composition",
        name="Period Summary Workflow",
        description="Planned workflow that summarizes tables, tasks and messages over a time range.",
        triggers=("weekly", "monthly", "period summary", "周报", "月报"),
        not_for=("meeting-only assumption", "invented facts"),
        resource_patterns=("date_range", "view_id"),
        required_context=("workspace_id",),
        optional_context=("date_range", "view_id"),
        negative_triggers=("send report now",),
        forbidden_actions=("invent_fact",),
        output_contract="planned_workflow_summary",
        confirmation_policy="not_executable",
        fallback="planned_skill",
    ),
    _manifest(
        skill_id="workflow-daily-briefing",
        source_skill="lark-workflow-standup-report",
        status="planned",
        layer="L4 Workflow Composition",
        name="Daily Briefing Workflow",
        description="Planned workflow for daily tasks, records and Telegram mentions.",
        triggers=("daily", "today", "standup", "日报", "今日"),
        not_for=("broad customer send",),
        resource_patterns=("date", "view_id", "task_id"),
        required_context=("workspace_id",),
        optional_context=("date", "view_id"),
        negative_triggers=("send to everyone",),
        forbidden_actions=("broad_group_send",),
        output_contract="planned_daily_briefing",
        confirmation_policy="not_executable",
        fallback="planned_skill",
    ),
)

_REGISTRY_BY_ID = {skill.skill_id: skill for skill in _REGISTRY}


def get_stage06_skill_registry() -> tuple[Stage06SkillManifest, ...]:
    return _REGISTRY


def get_stage06_active_skill_registry() -> tuple[Stage06SkillManifest, ...]:
    return tuple(skill for skill in _REGISTRY if skill.status == "active")


def get_stage06_skill_manifest(skill_id: str) -> Stage06SkillManifest:
    return _REGISTRY_BY_ID[skill_id]


def has_stage06_skill(skill_id: str) -> bool:
    return skill_id in _REGISTRY_BY_ID


__all__ = [
    "STAGE06_SKILL_MANIFEST_VERSION",
    "Stage06SkillManifest",
    "get_stage06_active_skill_registry",
    "get_stage06_skill_manifest",
    "get_stage06_skill_registry",
    "has_stage06_skill",
]
